### ISSUE TITLE
trigger MIDI crashes Ardour

### ISSUE THREAD

**Issue by lrfinotti** [sadko4u/lsp-plugins#28]
Trigger MIDI (mono) crashes Ardour.

The GDB log below was created by starting ardour, creating new session, adding mono track, and adding the trigger midi mono to that track (which crashed ardour).

Here is the log: [gdb1.txt](https://github.com/sadko4u/lsp-plugins/files/2845006/gdb1.txt)

**Comment by sadko4u** [comment]
Hello!
I don't see anything related to LSP in GDB log.
How do you reproduce the crash? Do you use other plugins in your setup?

**Comment by lrfinotti** [comment]
As I said in the original post, all I've done was start Ardour, create new (empty) session, create mono track and add the Trigger MIDI Mono plugin.  Adding the plugin crashes Ardour.

So, it's a new empty session, with no plugins or tracks in it.

The system is running Debian Sid and Ardour is the official binary.

Just let me know if there is anything I can do help debug it.

**Comment by sadko4u** [comment]
I've looked again into the stack trace. It seems to be a memory-corruption problem.
I think the best way to detect the problem is running Ardour under valgrind with --tool=memcheck option.
This will be much more useful for detecting the cause of problem.

**Comment by sadko4u** [comment]
I see, we've already fixed some issues related to LSP earlier. Please run Ardour under valgrind according to this post:
https://github.com/sadko4u/lsp-plugins/issues/9#issuecomment-431145004

**Comment by lrfinotti** [comment]
OK.  I will do it later tonight when I get home or tomorrow morning.

**Comment by sadko4u** [comment]
I've tried to reproduce the problem on my system but still can not.
Also It would be good if you redirect valgrind's output to the log file, for example in ardour5 script:
```
exec valgrind --tool=memcheck --log-file="$HOME/ardour-valgrind.log" $INSTALL_DIR/bin/ardour-5.12.0
```

On my system, I see in log:
```
==19766== Mismatched free() / delete / delete []
==19766==    at 0x4C2FC4B: operator delete[](void*) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==19766==    by 0x21EE7316: CMT_Descriptor::~CMT_Descriptor() (in /usr/lib64/ladspa/cmt.so)
==19766==    by 0x21EEBDB0: StartupShutdownHandler::~StartupShutdownHandler() (in /usr/lib64/ladspa/cmt.so)
==19766==    by 0xF82D061: __cxa_finalize (in /lib64/libc-2.26.so)
==19766==    by 0x21EE3012: ??? (in /usr/lib64/ladspa/cmt.so)
==19766==    by 0x4014F83: _dl_close_worker (in /lib64/ld-2.26.so)
==19766==    by 0x4015B9D: _dl_close (in /lib64/ld-2.26.so)
==19766==    by 0xF928BB3: _dl_catch_error (in /lib64/libc-2.26.so)
==19766==    by 0xA964664: _dlerror_run (in /lib64/libdl-2.26.so)
==19766==    by 0xA96408E: dlclose (in /lib64/libdl-2.26.so)
==19766==    by 0x10234315: g_module_close (in /opt/Ardour-5.12.0/lib/libgmodule-2.0.so.0)
==19766==    by 0x5B7D865: ARDOUR::PluginManager::ladspa_discover(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==19766==  Address 0x248b2f60 is 0 bytes inside a block of size 8 alloc'd
==19766==    at 0x4C2E01F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==19766==    by 0xF87C219: strdup (in /lib64/libc-2.26.so)
==19766==    by 0x21EE7410: CMT_Descriptor::CMT_Descriptor(unsigned long, char const*, int, char const*, char const*, char const*, CMT_ImplementationData*, void* (*)(_LADSPA_Descriptor const*, unsigned long), void (*)(void*), void (*)(void*, unsigned long), void (*)(void*, unsigned long), void (*)(void*, float), void (*)(void*)) (in /usr/lib64/ladspa/cmt.so)
==19766==    by 0x21EE4750: initialise_ambisonic() (in /usr/lib64/ladspa/cmt.so)
==19766==    by 0x21EE768D: initialise_modules() (in /usr/lib64/ladspa/cmt.so)
==19766==    by 0x21EE2F18: ??? (in /usr/lib64/ladspa/cmt.so)
==19766==    by 0x400FA79: call_init.part.0 (in /lib64/ld-2.26.so)
==19766==    by 0x400FB85: _dl_init (in /lib64/ld-2.26.so)
==19766==    by 0x4014308: dl_open_worker (in /lib64/ld-2.26.so)
==19766==    by 0xF928BB3: _dl_catch_error (in /lib64/libc-2.26.so)
==19766==    by 0x4013A88: _dl_open (in /lib64/ld-2.26.so)
==19766==    by 0xA963F95: dlopen_doit (in /lib64/libdl-2.26.so)
```
This is bad, but it's a some LADSPA plugin that I'll immediately remove because it corrupts memory with invalid delete[]/free() operation.

It would be nice to see what you'll get in your log.

**Comment by lrfinotti** [comment]
OK, I've been trying to get a proper log, but there are some issues.

First, running valgring, the log file 
[ardour-valgrind.log](https://github.com/sadko4u/lsp-plugins/files/2847778/ardour-valgrind.log) stops collecting errors before I add the plugin.  And then, if I keep running, I can't make it crash Ardour.

Yesterday the steps above (new session, add mono track, add trigger sensor mono) crashed Ardour 3 times on a row.  Now, it does not always crash.  But, *if I am not running valgrind*, I can crash it by doing the above, and if it does not crash, then adding a stereo track and adding trigger sensor MIDI stereo crashes it.

I will try to add --error-limit=no to valgrind, but I hope the file does not get too large...  (But again, it does not seem to crash using it...)

**Comment by lrfinotti** [comment]
A few more times and the same: using valgrind, I can't crash Ardour, without it I can every time...

This is probably not helpful, but here is the full valgrind log of a session (no crash) in which I add and remove many instances of trigger midi sensor: 
[ardour-valgrind2.log](https://github.com/sadko4u/lsp-plugins/files/2847802/ardour-valgrind2.log)

**Comment by sadko4u** [comment]
That's interesting:
```
==5764== Thread 12:
==5764== Invalid read of size 4
==5764==    at 0x3A096CCE: lsp::LV2MidiOutputPort::post_process(unsigned long) (in /usr/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so)
==5764==    by 0x3FF: ???
==5764==    by 0x3FF: ???
==5764==    by 0x1B6B13BF: ???
==5764==    by 0x3F80000000000000: ???
==5764==    by 0x32CE5667: ???
==5764==    by 0x32CE56F7: ???
==5764==  Address 0x29640e40 is 16 bytes inside a block of size 32,824 free'd
==5764==    at 0x48369AB: free (vg_replace_malloc.c:530)
==5764==    by 0x524FF9F: ARDOUR::BufferSet::ensure_lv2_bufsize(bool, unsigned long, unsigned long) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x576999E: ARDOUR::LV2Plugin::connect_and_run(ARDOUR::BufferSet&, long, long, double, ARDOUR::ChanMapping, ARDOUR::ChanMapping, unsigned int, long) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x557591E: ARDOUR::PluginInsert::connect_and_run(ARDOUR::BufferSet&, long, long, double, unsigned int, long, bool) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x5577005: ARDOUR::PluginInsert::run(ARDOUR::BufferSet&, long, long, double, unsigned int, bool) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x55EC25F: ARDOUR::Route::process_output_buffers(ARDOUR::BufferSet&, long, long, unsigned int, int, bool) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x55E619B: ARDOUR::Route::passthru(ARDOUR::BufferSet&, long, long, unsigned int, int) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x573B318: ARDOUR::Track::no_roll(unsigned int, long, long, bool) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x531500E: ARDOUR::Graph::process_one_route(ARDOUR::Route*) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x5314CDE: ARDOUR::Graph::run_one() (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x5316090: ARDOUR::Graph::main_thread() (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x1ABC67CE: ARDOUR::JACKAudioBackend::_start_process_thread(void*) (in /opt/Ardour-5.12.0/lib/backends/libjack_audiobackend.so)
==5764==  Block was alloc'd at
==5764==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==5764==    by 0x576D32E: lv2_evbuf_new (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x525102C: ARDOUR::BufferSet::ensure_buffers(ARDOUR::DataType, unsigned long, unsigned long) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x5738ACD: ARDOUR::ThreadBuffers::ensure_buffers(ARDOUR::ChanCount, unsigned long) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x524FC76: ARDOUR::BufferManager::ensure_buffers(ARDOUR::ChanCount, unsigned long) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x56D00E0: boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, ARDOUR::Session, ARDOUR::ChanCount>, boost::_bi::list2<boost::_bi::value<ARDOUR::Session*>, boost::arg<1> > >, void, ARDOUR::ChanCount>::invoke(boost::detail::function::function_buffer&, ARDOUR::ChanCount) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x53423CE: PBD::Signal1<void, ARDOUR::ChanCount, PBD::OptionalLastValue<void> >::operator()(ARDOUR::ChanCount) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x533AB41: ARDOUR::IO::ensure_ports_locked(ARDOUR::ChanCount, bool, bool&) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x533ADEA: ARDOUR::IO::ensure_ports(ARDOUR::ChanCount, bool, void*) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x564B9C1: ARDOUR::Session::setup_ltc() (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x564E053: ARDOUR::Session::immediately_post_engine() (in /opt/Ardour-5.12.0/lib/libardour.so.3)
==5764==    by 0x564E3AE: ARDOUR::Session::ensure_engine(unsigned int, bool) (in /opt/Ardour-5.12.0/lib/libardour.so.3)
```

- Could you try to reproduce the problem on the previous version of LSP Plugins (1.1.4)?
- Please remember me your audio setup (sample rate, number of buffers, buffer size).

That's something strange happening with the MIDI buffer between Trigger plugin and Ardour.

**Comment by sadko4u** [comment]
Also are you available to build plugins from some branch and install debug version of Ardour? It seems that we are going to debug all the stuff via printf() method.

**Comment by lrfinotti** [comment]
I installed v1.1.4 and had the same problem (again, add mono track then trigger sensor mono, then adding stereo track then trigger sensor stereo crashed Ardour).

For these tests I'm running jack (via Cadence) with sample rate of 44.1kHz, buffer size of 1024 samples and 3 periods.  The interface is a Focusrite 2i2 2nd generation.

And yes, I'd be glad to test the plugins from a different branch.  But I cannot find a debug version of Ardour.  If you point me to it, I'd be glad to install it too.

**Comment by sadko4u** [comment]
I've pushed changes to *github-issue-28* branch. The latest commit is: 4405329597b410cb5567dc441b796be9b9cea97b

To build and install plugins, launch:
```
make clean && make trace && make LV2_PATH=<path-to-lv2> install_lv2
```
The **<path-to-lv2>** is the target LV2 path where plugins should be installed. You can omit this parameter if your installation path is **/usr/local/lib/lv2**.

If you have Ardour subscription, you can download the debug version from this site:
https://nightly.ardour.org/

**Comment by lrfinotti** [comment]
OK, I've compiled the github-issue-28 branch, and the crash still happens.  (This time I've add a mono track and trigger sensor mono, and when I tried to add a stereo track, it crashed.)  

I've noticed the it outputs some errors to the terminal.  Here they are: 
[ardour-cl.log](https://github.com/sadko4u/lsp-plugins/files/2849177/ardour-cl.log)

I went to the nightly page, but the version is v6.0-pre0-1541.  Is this the one you'd want?

**Comment by sadko4u** [comment]
Now it crashed in another place. It would be nice to get a gdb back-trace, too.
Could you also temporary hide Harrisson plugins (which cause an Ardour warning in logs) from Ardour?
Also this message is confusing me:
```
convolution: samplerate mismatch preset:48000 host:44100
```
What's this?

**Comment by lrfinotti** [comment]
For some reason, now I cannot run Ardour in GDB...  I get:
```
ardour: [INFO]: Using SSE optimized routines
[New Thread 0x7fffe9645700 (LWP 6918)]
[New Thread 0x7fffe8e44700 (LWP 6919)]
[New Thread 0x7fffdbfff700 (LWP 6920)]
[New Thread 0x7fffda064700 (LWP 6921)]
[New Thread 0x7fffd9863700 (LWP 6922)]
Cannot xinstall SIGPIPE error handler
ardour: [INFO]: Loading default ui configuration file /opt/Ardour-5.12.0/etc/default_ui_config
ardour: [INFO]: Loading user ui configuration file /home/finotti/.config/ardour5/ui_config

(ardour-5.12.0:6887): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(ardour-5.12.0:6887): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Color shuttle bg not found
ardour: [INFO]: Loading color file /opt/Ardour-5.12.0/share/themes/dark-ardour.colors

(ardour-5.12.0:6887): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(ardour-5.12.0:6887): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
ardour: [INFO]: Loading ui configuration file /opt/Ardour-5.12.0/etc/clearlooks.rc
ardour: [INFO]: Loading ui configuration file /opt/Ardour-5.12.0/etc/clearlooks.rc
[New Thread 0x7fffd3dd3800 (LWP 6923)]
[New Thread 0x7fffd3d58700 (LWP 6924)]
[New Thread 0x7fffd3557700 (LWP 6925)]
[New Thread 0x7fffd34d6700 (LWP 6926)]
[Thread 0x7fffd3d58700 (LWP 6924) exited]

Thread 11 "ardour-5.12.0" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffd34d6700 (LWP 6926)]
__libc_read (nbytes=4, buf=0x7fffd34d5bc0, fd=11) at ../sysdeps/unix/sysv/linux/read.c:26
26      ../sysdeps/unix/sysv/linux/read.c: No such file or directory.
```
I am not sure what happened, as I could run it before.  I will ask on the Ardour forum.

About the convolution message: I really don't know, but I've been getting this for a long time.  I could not find what it wrong, but did not notice any problems.

**Comment by x42** [comment]
re-created.  New Ardour Session, add a Mono Audio Track (using strict-i/o), load the Mono MIDI Trigger plugin.  Show the plugin GUI, lower the threshold so that some MIDI events trigger.

-> due to struct-i/o the plugin cannot modify the tracks I/O ports.
-> The plugin's MIDI output is left unconnected
-> Ardour provides a "scratch buffer" for that Port
-> Ardour also gives the plugin the, identical "scratch buffer" for DSP to GUI Communication
(Ardour uses scratch/scribble buffers for everything that it is not interested in by itself)

The plugin's port 5 (Midi output) and port 35 (UI Output) use the same buffer.
This leads to a crash in the plugin when writing to the port a 2nd time.

It is very unusual for a Plugin to have more than one pair of Atom ports, so this issue did not yet come up.

Simple standalone example: https://gist.github.com/x42/b82769d2b3567b0a5c77c2bd857326ae
I'm leaning towards this being a bug in `lv2_atom_forge_raw`.  ping @drobilla

**Comment by lrfinotti** [comment]
For what is worth, here is the GDB run using Ardours dummy-backend: 
[ardour-gdb.log](https://github.com/sadko4u/lsp-plugins/files/2849428/ardour-gdb.log)

**Comment by x42** [comment]
Using a debug version (both plugin and ardour):
```
[TRC][trigger.cpp: 453] update_settings: trigger note=35
[TRC][sampler.cpp: 502] update_settings: Initializing samples...
[TRC][trigger.cpp: 542] trigger_on: midi_out = 0x55555ab008a0
[TRC][trigger.cpp: 547] trigger_on: midi buffer = 0x55555ab008d0
[TRC][/home/rgareus/src/lsp-plugins/include/container/lv2/ports.h: 768] post_process: MIDI Event: type=NOTE_ON, timestamp=241
[TRC][/home/rgareus/src/lsp-plugins/include/container/lv2/ports.h: 782] post_process: midi dump: 90 23 55 (3: 11)
[TRC][widgets/LSPKnob.cpp: 172] update_value: value=-9.999986, delta=-0.500000
[TRC][/home/rgareus/src/lsp-plugins/include/container/lv2/ui_ports.h: 147] set_value: write(19, 4, 0, 0.298539)
[TRC][/home/rgareus/src/lsp-plugins/include/container/lv2/ui_wrapper.h: 221] notify: notify id=2, size=4, format=0, buf=0x7fffffffcd94 value=0.496026
[TRC][/home/rgareus/src/lsp-plugins/include/container/lv2/ui_ports.h: 217] notify: id=ism, value=0.496026
[TRC][/home/rgareus/src/lsp-plugins/include/container/lv2/ui_wrapper.h: 221] notify: notify id=19, size=4, format=0, buf=0x7fffffffcd84 value=0.298539

Thread 25 "ardour-6.0.pre0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffaceffd80 (LWP 30401)]
0x00007fff81ad4e10 in lv2_atom_forge_raw (forge=0x55555aab9ce0, data=0x7fffacefdac0, size=8) at /usr/lib/lv2/atom.lv2/forge.h:308
308			lv2_atom_forge_deref(forge, f->ref)->size += size;
(gdb) bt
#0  0x00007fff81ad4e10 in lv2_atom_forge_raw(LV2_Atom_Forge*, void const*, uint32_t) (forge=0x55555aab9ce0, data=0x7fffacefdac0, size=8) at /usr/lib/lv2/atom.lv2/forge.h:308
#1  0x00007fff81ad4e95 in lv2_atom_forge_write(LV2_Atom_Forge*, void const*, uint32_t) (forge=0x55555aab9ce0, data=0x7fffacefdac0, size=8) at /usr/lib/lv2/atom.lv2/forge.h:326
#2  0x00007fff81ad635a in lsp::LV2Extensions::forge_frame_time(long) (this=0x55555aab9ce0, frames=241) at /home/rgareus/src/lsp-plugins/include/container/lv2/extensions.h:439
#3  0x00007fff81ad9c88 in lsp::LV2MidiOutputPort::post_process(unsigned long) (this=0x55555ab008a0, samples=1024) at /home/rgareus/src/lsp-plugins/include/container/lv2/ports.h:785
#4  0x00007fff81add62f in lsp::LV2Wrapper::run(unsigned long) (this=0x55555aafc6e0, samples=1024) at /home/rgareus/src/lsp-plugins/include/container/lv2/wrapper.h:946
#5  0x00007fff81ae4a81 in lsp::lv2_run(void*, unsigned int) (instance=0x55555aafc6e0, sample_count=1024) at lv2.cpp:114
#6  0x00007ffff7119e93 in lilv_instance_run(LilvInstance*, uint32_t) (instance=0x55555aaba160, sample_count=1024) at /usr/include/lilv-0/lilv/lilv.h:1694
#7  0x00007ffff712a41a in ARDOUR::LV2Plugin::run(unsigned int, bool) (this=0x55555aa882d0, nframes=1024, sync_work=false) at ../libs/ardour/lv2_plugin.cc:3117
#8  0x00007ffff7127fff in ARDOUR::LV2Plugin::connect_and_run(ARDOUR::BufferSet&, long, long, double, ARDOUR::ChanMapping const&, ARDOUR::ChanMapping const&, unsigned int, long) (this=0x55555aa882d0, bufs=..., start=256, end=1280, speed=0, in_map=..., out_map=..., nframes=1024, offset=0) at ../libs/ardour/lv2_plugin.cc:2766
#9  0x00007ffff6e9ba7f in ARDOUR::PluginInsert::connect_and_run(ARDOUR::BufferSet&, long, long, double, unsigned int, long, bool) (this=
    0x55555aa7f9f0, bufs=..., start=256, end=1280, speed=0, nframes=1024, offset=0, with_auto=true) at ../libs/ardour/plugin_insert.cc:1032
#10 0x00007ffff6e9ced9 in ARDOUR::PluginInsert::run(ARDOUR::BufferSet&, long, long, double, unsigned int, bool) (this=0x55555aa7f9f0, bufs=..., start_sample=256, end_sample=1280, speed=0, nframes=1024) at ../libs/ardour/plugin_insert.cc:1236
#11 0x00007ffff6f37d59 in ARDOUR::Route::process_output_buffers(ARDOUR::BufferSet&, long, long, unsigned int, bool, bool) (this=
    0x55555b732bb0, bufs=..., start_sample=256, end_sample=1280, nframes=1024, gain_automation_ok=false, run_disk_reader=false) at ../libs/ardour/route.cc:493
#12 0x00007ffff6f38de7 in ARDOUR::Route::run_route(long, long, unsigned int, bool, bool) (this=0x55555b732bb0, start_sample=0, end_sample=1024, nframes=1024, gain_automation_ok=false, run_disk_reader=false) at ../libs/ardour/route.cc:679
#13 0x00007ffff6f4b98c in ARDOUR::Route::no_roll_unlocked(unsigned int, long, long, bool) (this=0x55555b732bb0, nframes=1024, start_sample=0, end_sample=1024, session_state_changing=false)
    at ../libs/ardour/route.cc:3794
#14 0x00007ffff6f4b869 in ARDOUR::Route::no_roll(unsigned int, long, long, bool) (this=0x55555b732bb0, nframes=1024, start_sample=0, end_sample=1024, session_state_changing=false)
    at ../libs/ardour/route.cc:3764
#15 0x00007ffff6b43b52 in ARDOUR::Graph::process_one_route(ARDOUR::Route*) (this=0x555559dbde30, route=0x55555b732bb0) at ../libs/ardour/graph.cc:574
#16 0x00007ffff6b49318 in ARDOUR::GraphNode::process() (this=0x55555b733088) at ../libs/ardour/graphnode.cc:79
#17 0x00007ffff6b421ef in ARDOUR::Graph::run_one() (this=0x555559dbde30) at ../libs/ardour/graph.cc:420
#18 0x00007ffff6b4274b in ARDOUR::Graph::main_thread() (this=0x555559dbde30) at ../libs/ardour/graph.cc:479
#19 0x00007ffff6b48ae9 in boost::_mfi::mf0<void, ARDOUR::Graph>::operator()(ARDOUR::Graph*) const (this=0x7fffaceff1d8, p=0x555559dbde30) at /usr/include/boost/bind/mem_fn_template.hpp:49
#20 0x00007ffff6b48224 in boost::_bi::list1<boost::_bi::value<ARDOUR::Graph*> >::operator()<boost::_mfi::mf0<void, ARDOUR::Graph>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, ARDOUR::Graph>&, boost::_bi::list0&, int) (this=0x7fffaceff1e8, f=..., a=...) at /usr/include/boost/bind/bind.hpp:259
#21 0x00007ffff6b475f9 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, ARDOUR::Graph>, boost::_bi::list1<boost::_bi::value<ARDOUR::Graph*> > >::operator()() (this=0x7fffaceff1d8)
    at /usr/include/boost/bind/bind.hpp:1294
#22 0x00007ffff6b46db9 in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void, boost::_mfi::mf0<void, ARDOUR::Graph>, boost::_bi::list1<boost::_bi::value<ARDOUR::Graph*> > >, void>::invoke(boost::detail::function::function_buffer&) (function_obj_ptr=...) at /usr/include/boost/function/function_template.hpp:159
#23 0x0000555555b59212 in boost::function0<void>::operator()() const (this=0x7fffaceff1d0) at /usr/include/boost/function/function_template.hpp:771
#24 0x00007fffc4c3c573 in ARDOUR::DummyAudioBackend::dummy_process_thread(void*) (arg=0x55555b10a680) at ../libs/backends/dummy/dummy_audiobackend.cc:552
#25 0x00007fffeee58494 in start_thread (arg=0x7fffaceffd80) at pthread_create.c:333
#26 0x00007fffebb7cacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```
Since the Atom was already initialized (atom.size = 8), one cannot write more than 8bytes. re-using the same port to wrote a larger message fails (message is not written).

This lead to a null pointer dereference in `lv2_atom_forge_deref()`
```
(gdb) print f->ref
$1 = 0
(gdb) p forge->buf
$2 = (uint8_t *) 0x7fff98000ca0 <incomplete sequence \361>
(gdb) 
```

**Comment by x42** [comment]
For now, you can work-around by connecting the plugin's MIDI-output (use flexible i/o in Ardour, or manually connect plugin-pins).

**Comment by sadko4u** [comment]
Robin, great thanks for reproducing the issue!
Currently, what I see now:
- there's a workaround for user: use Flexible I/O instead of Strict I/O;
- there's a bug in Ardour that does not properly handle multiple Atom ports, that should be fixed;
- I should look forward to change MIDI transport and avoid usage of more than one input Atom port and one output Atom port.

Right?

**Comment by x42** [comment]
> there's a bug in Ardour that does not properly handle multiple Atom ports, that should be fixed;

I currently think Ardour is fine and the issue is in lv2-sdk (forge.h)
Writing to a port that has insufficient size should just be a no-op (and not crash).

 Strictly speaking it's a plugin issue, the plugin needs to be re-compiled with an updated lv2-sdk once forge.h was fixed. -- That being said it may be prudent for a host (here Ardour) to not use the same buffer for multiple Atom Output ports.  Yet in theory that should be fine  since nobody cares what is written to that port buffer anyway.  I'm interested in David 'lv2' Robillard's opinion (since he wrote that code in Ardour and also wrote the forge header).

**Comment by sadko4u** [comment]
Anyway, now we can consider this case as a bug for LSP Plugins, so I need to re-work MIDI transport.

**Comment by sadko4u** [comment]
I've pushed commit to the **github-issue-28** branch: 9677a9268018c5183fcd004f52b129ad0685fd38

In this commit I've changed MIDI transport so now plugin utilizes only two Atom ports: one for input, and one for output. I've checked on my system and it seems to be working. But to be sure, please ensure that the new version does not crash Ardour any more.

Additionally, I've found a problem of syncing time/beat position between UI and DSP for the VST version of plugins, so this change contains also fix for this.
Also, I've detected another regression in the **devel** branch related to character set conversions and fixed it.

**Comment by sadko4u** [comment]
And... Small hotfix for the TTL generator: fcea35d98c769a932573859efd85ef6ff598dae7

**Comment by lrfinotti** [comment]
OK, unless I messed up getting the new version, it still crashes following the same steps: add mono track, add trigger sensor mono, add stereo track, add trigger sensor stereo.

Here is the GDB log: 
[ardour-gdb2.log](https://github.com/sadko4u/lsp-plugins/files/2872926/ardour-gdb2.log)

**Comment by sadko4u** [comment]
@lrfinotti i doubt that you have built plugins from proper branch.
You need to ensure that ```git log``` is showing latest changes:
```
commit fcea35d98c769a932573859efd85ef6ff598dae7 (HEAD -> github-issue-28, origin/github-issue-28)
Author: sadko4u <...>
Date:   Sun Feb 17 02:24:51 2019 +0300

    Fixed LV2 TTL generator

commit 9677a9268018c5183fcd004f52b129ad0685fd38
Author: sadko4u <...>
Date:   Sun Feb 17 02:10:14 2019 +0300

    Changes affected by this commit:
    
    * Changed implementation of LV2 MIDI transport so now plugins utilize
    only one
      LV2:Atom input port and one LV2:Atom output port.
    * Fixed bug in host<->UI time and position synchronization.
```

If that's not right, then you need to properly checkout **github-issue-28** branch.
The simpliest way you can go, is just remove current code repository and perform the following commands:
```
git clone https://github.com/sadko4u/lsp-plugins.git
cd lsp-plugins
git checkout -b github-issue-28 origin/github-issue-28
make clean
make
make uninstall_lv2
make install_lv2
```

**Comment by lrfinotti** [comment]
I should learn git better one of these days...  Indeed, it seems I had the wrong version.  After the commands above I could not make it crash!

Thanks @sadko4u and @x42 for your help!

**Comment by sadko4u** [comment]
Nice!
Merged all changes into *devel* branch: a5743795c68132dab1075290626e1aec5db0b44e
All changes will be available in the next release.

**Comment by sadko4u** [comment]
All changes are available in the 1.1.7 release that was just published.
