### ISSUE TITLE
[GUI Bug] Some knobs remain gray despite being working.

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#341]
It's a minor bug but I thought I should report it.

For Gate plugins is the Hi-pass/Low-pass filter mode and frequency.

![011](https://github.com/sadko4u/lsp-plugins/assets/123143444/46cc51d7-8fa0-4bdb-92bf-c900c9b468d5)

For Multiband plugins except Dynamic Processors and Limiter is the Hi-pass frequency.

![010](https://github.com/sadko4u/lsp-plugins/assets/123143444/b5bf5544-0637-49f3-9c8d-105cd66a2295)

**Comment by sadko4u** [comment]
HCF = High Cut Frequency
HPF = High Pass Filter.
I think it is a good reason to make names similar.

**Comment by sadko4u** [comment]
Hmm. I don't see the knobs grayed out. At least for Gate plugin not working knob should have different background.

**Comment by p-chan5** [comment]
Exactly, they should have a different color. The knobs work but remain gray on the interface.

An expected behavior would be, for example, with Compressor plugin series.

![002](https://github.com/sadko4u/lsp-plugins/assets/123143444/68b32416-8711-4c51-abb8-a0166d263c28)

**Comment by p-chan5** [comment]
As I say, it is a minimal bug, that is, it does not affect the behavior of the plugins in any way, it is just something visual.

**Comment by sadko4u** [comment]
Is the problem reproducible after 1.2.11 release?

**Comment by p-chan5** [comment]
I am currently running `lsp-plugins-vst2-1.2.11-Linux-x86_64` and the bug is still reproducible.

I'm afraid to say that I don't have the necessary knowledge to compile the devel branch and report if it has been fixed.

**Comment by sadko4u** [comment]
Could you please make a short video demonstrating the bug?

**Comment by p-chan5** [comment]
Of course! Look at `HPF` and `LPF` of both plugins, the bug is in the Gate ones, that is, the colors of the text and the `HPF` knob do not correspond to those of the compressor.

https://github.com/sadko4u/lsp-plugins/assets/123143444/be072540-7bde-4b02-a9a4-8f7b2e103b6e

For Multiband plugins the behavior of `LCF` and `HCF` is different, since sometimes it changes color and sometimes it doesn't.

https://github.com/sadko4u/lsp-plugins/assets/123143444/14c25d41-43a0-49f7-9332-5ccc0dce687e

**Comment by sadko4u** [comment]
Oh, now I see. Seems to be a simple error in the XML markup file which is related to controlling the process of graying-out colors for elements.

**Comment by sadko4u** [comment]
It seems that @bor-T has fixed all related problems in the UI of multiband plugins today:

https://github.com/lsp-plugins/lsp-plugins-mb-compressor/commit/80a414634f858256bef5b41e0851e4284be6f3f6
https://github.com/lsp-plugins/lsp-plugins-mb-expander/commit/b0de7dca6f6b9952723f6df2605c0a1473f0a9d1
https://github.com/lsp-plugins/lsp-plugins-mb-gate/commit/e9b9417b146fe07e48624bbabdb49ebfde9da5d9

**Comment by p-chan5** [comment]
Great! Thank you very much for fixing this bug <3

**Comment by sadko4u** [comment]
Fixed in 1.2.12.

**Comment by p-chan5** [comment]
@sadko4u @bor-T I'm running `lsp-plugins-vst2-1.2.13-Linux-x86_64.tar.gz` and I can still reproduce this bug on some Gate plugins:

- Gate Mono
- Gate Stereo
- Sidechain Gate Mono
- Sidechain Gate Stereo

As I explained before, it's a bug with the colors of the `dB/oct` boxes and the `HPF` and `LPF` knobs.

You can check out the compressor plugins. Those are the right colors.

Gate Stereo:
![gate](https://github.com/sadko4u/lsp-plugins/assets/123143444/8e4f2a9e-23e8-4469-807b-e64535586844)

Compressor Stereo:
![compressor](https://github.com/sadko4u/lsp-plugins/assets/123143444/20e2b893-e658-4225-93ef-a8e76ab0a1b2)

**Comment by sadko4u** [comment]
@bor-T please take a look at it.

**Comment by bor-T** [comment]
Fixed it.

**Comment by p-chan5** [comment]
Thanks a lot! <3
